In [1]:
import numpy as np
import pandas as pd

###`Q-1:` Write a program to create an empty series.

In [2]:
# code here
empty_series = pd.Series()
empty_series

Series([], dtype: object)

###`Q-2:` Write a Pandas program to add, subtract, multiple and divide two Pandas Series.

In [7]:
# code here
# add
s1 = pd.Series([10,20,30,40,50,60])
s2 = pd.Series([70,80,90,100,120,130])

s1 + s2

# subtract
# s1 - s2

# multiply
s1 * s2

# divide 
s1/s2

0    0.142857
1    0.250000
2    0.333333
3    0.400000
4    0.416667
5    0.461538
dtype: float64

###`Q-3` Write a Pandas program to compare the elements of the two Pandas Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 10]

In [8]:
# code here
s1 = pd.Series([2,4,6,8,10])
s2 = pd.Series([1,3,5,7,10])

s1 == s2

0    False
1    False
2    False
3    False
4     True
dtype: bool

###`Q-5.`Write a function to change the data type of given a column or a Series. Function takes series and data type as input, returns the converted series.
```
series = pd.Series([1,2,'Python', 2.0, True, 100])
change to float type data
```
Note: Read about pd.to_numeric()

In [13]:
# code here
def change_elements_data_type(series, dataType):
    valid_types = ['integer', 'signed', 'unsigned', 'float']
    
    if dataType not in valid_types:
        raise ValueError(f"Invalid dataType '{dataType}'. Choose from {valid_types}")
    
    return pd.to_numeric(series, downcast=dataType, errors='coerce')

s1 = pd.Series([1,2,'Python',2.0,True,100])
res = change_elements_data_type(s1,'float')
res

0      1.0
1      2.0
2      NaN
3      2.0
4      1.0
5    100.0
dtype: float32

Download data - https://drive.google.com/file/d/1LRhXwbEodeWXtzPhJCX0X9Lf_BECzvqb/view?usp=share_link
All Batsman runs series in IPL 2008 to 2022.

Below questions are based on this data.

###`Q-6` Find top 10 most run getter from the series.

In [ ]:
# code here

###`Q-7` No of players having runs above 3000

In [ ]:
# code here

###`Q-8` No of players having runs above mean value?

In [ ]:
# code here

Download data - https://drive.google.com/file/d/1QZuZ5bypUInfVvarHACLAi8tXXHvb8xd/view?usp=share_link

file name - items.csv

###`Q-9`
    i. Read `items.csv` making `item_name` as index.
    ii. Show no of nan values
    ii. Item price is given in $, so convert it to rupees without currency symbol.
    iii. Make data type of newly made series as float.
    iv. Fill nan with mean of the series


How csv file looks

```
item_name	item_price
Chips and Fresh Tomato Salsa	$2.39
Izze	$3.39
Nantucket Nectar	$3.39
Chips and Tomatillo-Green Chili Salsa	$2.39
Chicken Bowl	$16.98

```

In [ ]:
# code here

###`Q-10`:
    i. Find mean price
    ii. Find 30th and 6th percentile value
    iii. Plot Histogram on price with bin size 50
    iv. No of items price lies between [1000 to 2000]

In [ ]:
# code here