In [2]:
import numpy as np
import pandas as pd

###`Q-1:` Write a program to create an empty series.

In [ ]:
# code here
# Pandas doesn't know what type you'll store, so it defaults to float64 — the most flexible numeric type
empty_series = pd.Series()
empty_series

Series([], dtype: object)

###`Q-2:` Write a Pandas program to add, subtract, multiple and divide two Pandas Series.

In [ ]:
# code here
# add
s1 = pd.Series([10,20,30,40,50,60])
s2 = pd.Series([70,80,90,100,120,130])

s1 + s2

# subtract
# s1 - s2

# multiply
s1 * s2

# divide
s1/s2

0    0.142857
1    0.250000
2    0.333333
3    0.400000
4    0.416667
5    0.461538
dtype: float64

###`Q-3` Write a Pandas program to compare the elements of the two Pandas Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 10]

In [ ]:
# code here
s1 = pd.Series([2,4,6,8,10])
s2 = pd.Series([1,3,5,7,10])

s1 == s2

0    False
1    False
2    False
3    False
4     True
dtype: bool

###`Q-5.`Write a function to change the data type of given a column or a Series. Function takes series and data type as input, returns the converted series.
```
series = pd.Series([1,2,'Python', 2.0, True, 100])
change to float type data
```
Note: Read about pd.to_numeric()

In [ ]:
# code here
def change_elements_data_type(series, dataType):
    valid_types = ['integer', 'signed', 'unsigned', 'float']

    if dataType not in valid_types:
        raise ValueError(f"Invalid dataType '{dataType}'. Choose from {valid_types}")

    return pd.to_numeric(series, downcast=dataType, errors='coerce')

s1 = pd.Series([1,2,'Python',2.0,True,100])
res = change_elements_data_type(s1,'float')
res

0      1.0
1      2.0
2      NaN
3      2.0
4      1.0
5    100.0
dtype: float32

Download data - https://drive.google.com/file/d/1LRhXwbEodeWXtzPhJCX0X9Lf_BECzvqb/view?usp=share_link
All Batsman runs series in IPL 2008 to 2022.

Below questions are based on this data.

###`Q-6` Find top 10 most run getter from the series.

In [ ]:
# code here
runs = pd.read_csv('/content/batsman_runs_series - batsman_runs_series.csv',index_col='batter').squeeze()
runs.sort_values(ascending=False).head(10)

batter
V Kohli           6634
S Dhawan          6244
DA Warner         5883
RG Sharma         5881
SK Raina          5536
AB de Villiers    5181
CH Gayle          4997
MS Dhoni          4978
RV Uthappa        4954
KD Karthik        4377
Name: batsman_run, dtype: int64

###`Q-7` No of players having runs above 3000

In [ ]:
# code here
runs[runs > 3000].size

20

###`Q-8` No of players having runs above mean value?

In [ ]:
# code here
runs[runs > runs.mean()].size

128

Download data - https://drive.google.com/file/d/1QZuZ5bypUInfVvarHACLAi8tXXHvb8xd/view?usp=share_link

file name - items.csv

###`Q-9`
    i. Read `items.csv` making `item_name` as index.
    ii. Show no of nan values
    ii. Item price is given in $, so convert it to rupees without currency symbol.
    iii. Make data type of newly made series as float.
    iv. Fill nan with mean of the series


How csv file looks

```
item_name	item_price
Chips and Fresh Tomato Salsa	$2.39
Izze	$3.39
Nantucket Nectar	$3.39
Chips and Tomatillo-Green Chili Salsa	$2.39
Chicken Bowl	$16.98

```

In [33]:
# code here
items = pd.read_csv('/content/items.csv',index_col='item_name').squeeze()

# show number of nan values
items[pd.isna(items)].sum()

# converting price to rupee with changing symbol
# non_nan_prices = items[~(pd.isna(items))]
rupee_prices = (
    items
    .str.replace('$','',regex=False)
    .astype(float)
    .where(lambda x: x.isna(),lambda x : x.mul(90))
)
rupee_prices

# Make data type of newly made series as float.
# rupee_prices = rupee_prices.astype(float)


#  Fill nan with mean of the series
rupee_prices.fillna(rupee_prices.mean(),inplace=True)

###`Q-10`:
    i. Find mean price
    ii. Find 30th and 6th percentile value
    iii. Plot Histogram on price with bin size 50
    iv. No of items price lies between [1000 to 2000]

In [53]:
# code here
items

# Find mean price
mean_price = rupee_prices.mean()
mean_price

# Find 30th and 6th percentile value
# rupee_prices.quantile(0.30)
# rupee_prices.quantile(0.06)
rupee_prices.quantile(0.90)


#  Plot Histogram on price with bin size 50
# rupee_prices.hist(bins=[10,60,110,160])

# No of items price lies between [1000 to 2000]


# rupee_prices[rupee_prices.between(1000,2000)].size

# ------------- OR ------------

# rupee_prices.between(1000,2000).sum() #counts all True

np.float64(1033.2)