In [ ]:
import numpy as np
import pandas as pd

# to visualize all the column, run the below code
pd.options.display.max_columns = None
# to show all the records, use the below code
# pd.options.display.max_rows = None

## Fifa Worldcup - 2022 dataset.

You can find the dataset from [here](https://www.kaggle.com/datasets/sayanroy729/fifa-worldcup-2022-results).

Also you can directly use an url to read the dataset by using `pd.read_csv()` method. Check the below code cell.

In [ ]:
# To get the details about the dataset, please visit
# https://www.kaggle.com/datasets/sayanroy729/fifa-worldcup-2022-results

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv"
football = pd.read_csv(url)
football.head()

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Red Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,5,0,5,2,3,15,0,3,1,9,45,5,159,100,6,4,4,0,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,5,5,2,4,1,8,7,6,4,6,55,10,159,103,6,4,2,0,15,4,484,419,26,10,3,17,1,3
2,3,2,England,Iran,B,6,69,6,0,6,13,7,3,10,3,11,5,2,3,11,72,15,133,94,8,6,0,0,9,2,810,733,29,9,8,16,0,3
3,4,2,Iran,England,B,2,20,2,0,1,8,3,4,6,2,3,0,3,1,1,34,1,56,19,1,1,2,0,14,2,232,156,11,3,0,10,1,0
4,5,3,Senegal,Netherlands,A,0,39,0,0,0,15,4,7,8,7,12,4,2,4,13,101,12,143,86,6,6,2,0,13,2,391,326,22,8,6,14,0,0

### `Q-1:` Use the football dataset. Find out the total percentages that each team made on target. Display the result as a python dictionary where the keys are the team list and the values are the percentage values. Round off the percentage values up to 2 decimal places.

*Help:*
- First, find out how many total teams are participated in this worldcup. For that, you can use `unique()` method on the column "Team" or "Against".
- Loop through the teams list that you have found in previous section, and then filter the dataset according to that. After filtering the dataset, find out total attempts sum and total on target sum.
- After getting these values, find out the percentage by total on target divided by total attempts and multiply by 100. And store to a python dictionary where the key will be the team name and the values will be the percentages.
- At the end,sort the dictionary by the values (not by the keys) and print the result.


**Sample Output:**
```bash
{'Costa Rica': 54.55,
 'Cameroon': 51.85,
 'Ecuador': 48.15,
 'Argentina': 46.99,
 'Brazil': 45.56,
 'England': 45.0,
 'Portugal': 40.32,
 'Ghana': 40.0,
 'Netherlands': 39.02,
 'Korea Republic': 36.73,
 'Australia': 36.0,
 'Mexico': 34.88,
 'Croatia': 34.78,
 'Germany': 34.33,
 'France': 32.97,
 'Spain': 32.69,
 'Belgium': 32.35,
 'Serbia': 32.26,
 'Iran': 31.43,
 'Uruguay': 31.25,
 'United States': 31.11,
 'Saudi Arabia': 31.03,
 'Senegal': 30.77,
 'Denmark': 30.56,
 'Switzerland': 30.56,
 'Japan': 30.23,
 'Wales': 29.17,
 'Qatar': 28.57,
 'Morocco': 28.3,
 'Tunisia': 26.67,
 'Poland': 25.0,
 'Canada': 17.65}
```

In [ ]:
# code here
football.head()
allTeams = football['Team'].unique()
res = {}
for each_team in allTeams:
  attemptsTaken = sum(football[(football['Team'] == each_team)]['Total Attempts'])
  target_shots = sum(football[(football['Team'] == each_team)]['On Target'])
  percentageTotal = round(((target_shots)/attemptsTaken) * 100,2)
  res[each_team] = percentageTotal

res = dict(sorted(res.items(),key = lambda x : x[1],reverse=True))

res

{'Costa Rica': 54.55,
 'Cameroon': 51.85,
 'Ecuador': 48.15,
 'Argentina': 46.15,
 'Brazil': 45.56,
 'England': 45.0,
 'Portugal': 40.32,
 'Ghana': 40.0,
 'Netherlands': 39.02,
 'Korea Republic': 36.73,
 'Australia': 36.0,
 'Mexico': 34.88,
 'France': 34.65,
 'Germany': 34.33,
 'Croatia': 33.73,
 'Spain': 32.69,
 'Belgium': 32.35,
 'Serbia': 32.26,
 'Iran': 31.43,
 'Uruguay': 31.25,
 'United States': 31.11,
 'Saudi Arabia': 31.03,
 'Senegal': 30.77,
 'Denmark': 30.56,
 'Switzerland': 30.56,
 'Japan': 30.23,
 'Wales': 29.17,
 'Qatar': 28.57,
 'Morocco': 28.33,
 'Tunisia': 26.67,
 'Poland': 25.0,
 'Canada': 17.65}

### `Q-2:` Find out how many times the teams are played in this Fifa Worldcup-2022. On top of this, find out the ranks of the teams.

Note: The `DataFrame.rank()` method takes an optiinal parameter named `method`. This parameter takes different values, but one of them is `average` which is by-default. So, when you do the rank, you will get some 2.5 like floating values. But if you change the value as `first`, then you will get in integers but the datatype will be float. So, try with `method="first"` parameter.

In [ ]:
# code here

# How many teams played in fifa world cup

# football['Team'].nunique()

# football['Rank']  = football['Pts'].rank(method='first')
# football[['Rank','Team']]

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Red Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,5,0,5,2,3,15,0,3,1,9,45,5,159,100,6,4,4,0,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,5,5,2,4,1,8,7,6,4,6,55,10,159,103,6,4,2,0,15,4,484,419,26,10,3,17,1,3
2,3,2,England,Iran,B,6,69,6,0,6,13,7,3,10,3,11,5,2,3,11,72,15,133,94,8,6,0,0,9,2,810,733,29,9,8,16,0,3
3,4,2,Iran,England,B,2,20,2,0,1,8,3,4,6,2,3,0,3,1,1,34,1,56,19,1,1,2,0,14,2,232,156,11,3,0,10,1,0
4,5,3,Senegal,Netherlands,A,0,39,0,0,0,15,4,7,8,7,12,4,2,4,13,101,12,143,86,6,6,2,0,13,2,391,326,22,8,6,14,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,124,62,Morocco,Fram,F,0,55,0,0,0,13,1,6,8,5,10,4,6,6,19,74,15,141,95,18,11,1,0,11,3,583,518,22,1,3,15,0,0
124,125,63,Croatia,Morocco,F,2,45,2,0,2,14,4,8,7,7,20,8,3,2,7,106,15,164,114,23,12,0,0,13,2,491,430,21,3,6,13,0,3
125,126,63,Morocco,Croatia,F,1,45,1,0,0,7,2,5,5,2,13,1,3,7,16,75,10,150,97,14,8,2,0,11,2,494,428,20,5,3,15,0,0
126,127,64,Argentina,France,C,3,46,3,0,1,21,9,9,13,8,13,6,8,9,9,163,28,249,172,40,24,4,0,26,4,648,544,20,4,6,22,5,3
127,128,64,France,Argentina,D,3,40,3,0,1,10,5,3,7,3,15,7,5,4,12,69,9,179,107,14,9,3,0,19,4,516,419,24,3,5,28,4,0

### `Q-3:` Find out these below topics:
- The information about the Fifa worldcup dataset.
- The description about the Fifa worldcup dataset
- Check is there any missing values, if there is any missing values, fill that value with the average value for that particular column.
- Drop all the duplicate rows permanently.
- Drop the columns: "Sl No", "Match No.", "Red Cards" and "Pts" permanently.

In [ ]:
# code here
# The information about the Fifa worldcup dataset.

# football.info()

# The description about the Fifa worldcup dataset

# football.describe()

# Check is there any missing values, if there is any missing values, fill that value with the average value for that particular column.

# for each_col in football.columns:
#   if football[each_col].hasnans:
#     football[each_col].fillna(football[each_col].mean(),inplace=True)

# Drop all the duplicate rows permanently.

# football.drop_duplicates(inplace=True)

# Drop the columns: "Sl No", "Match No.", "Red Cards" and "Pts" permanently.

football.drop(columns=['Sl. No','Match No.','Red Cards','Pts'],inplace=True)
football.columns

Index(['Team', 'Against', 'Group', 'Goal', 'Possession (%)',
       'Inside Penalty Area', 'Outside Penalty Area', 'Assists',
       'Total Attempts', 'On Target', 'Off Target', 'Target in Penalty',
       'Target from Outside', 'Left Channel', 'Left Inside Channel',
       'Central Channel', 'Right Inside Channel', 'Right Channel',
       'Receptions MD', 'Receptions D', 'Attempted Line Breaks',
       'Completed Line Breaks', 'Attempted Defensive Line Breaks',
       'Completed Defensive Line Breaks', 'Yellow Cards', 'Fouls Against',
       'Offsides', 'Passes', 'Passes Completed', 'Crosses',
       'Crosses Completed', 'Corners', 'Free Kicks', 'Penalties Scored',
       'Rank'],
      dtype='object')

###`Q-4:` Do these below operations:
- Find out the rank based on the "Team" column and save the result by adding a new column named "Rank".
- Change the datatype of this column to integer by using `np.int16`
- Set the index of the DataFrame by using this "Rank" column permanently.
- After that, sort the dataframe based on the "Rank" index.

In [ ]:
# code here

# Find out the rank based on the "Team" column and save the result by adding a new column named "Rank".

# football['Rank'] = football['Team'].rank()
# football[['Rank','Team']]

# Change the datatype of this column to integer by using np.int16

# football['Rank'].astype(np.int16)

# Set the index of the DataFrame by using this "Rank" column permanently.

# football.set_index('Rank',inplace=True)

## Questions on Titanic dataset.

You can get the dataset from [here](https://www.kaggle.com/competitions/titanic). This is the competition page on Kaggle. To download the dataset from here, I guess you have to register for the compition. So, do so and then download the dataset.

Also, for now you can use this url to read the dataset like before:
- dataset 1: https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv
- dataset 2: https://docs.google.com/spreadsheets/d/e/2PACX-1vQcPvQsSC9aNFogvbUG08nu0bGHlOclGYaOlhND_LE5Ff7ZnHQ5VYzAgpyT5XNklgiT54SsNgHePsUa/pub?gid=1656109608&single=true&output=csv

In [ ]:
t1 = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv')
t2 = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vQcPvQsSC9aNFogvbUG08nu0bGHlOclGYaOlhND_LE5Ff7ZnHQ5VYzAgpyT5XNklgiT54SsNgHePsUa/pub?gid=1656109608&single=true&output=csv')

### `Q-5:` Do the below tasks:
1. With dataset 1, drop those records which only have missing values of the "Age" column permanently.

2. With the dataset 2, fill the missing values with 20 to the only "Age" column permanently.

In [ ]:
# code here

# With dataset 1, drop those records which only have missing values of the "Age" column permanently.

# t1.dropna(subset='Age',inplace=True)

# With the dataset 2, fill the missing values with 20 to the only "Age" column permanently.

# t2['Age'].fillna(20,inplace=True)

# -------- OR ----------
# t2.fillna({'Age': 20}, inplace=True)

/tmp/ipykernel_4032/1442496216.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  t2['Age'].fillna(20,inplace=True)

## Questions on IPL wala dataset

matches dataset = https://drive.google.com/file/d/1yKVUuexl6lIKuFQy7uIPgDgXhJ0L4SIg/view?usp=share_link

Code to directly use in colab
```
ipl_matches = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRy2DUdUbaKx_Co9F0FSnIlyS-8kp4aKv_I0-qzNeghiZHAI_hw94gKG22XTxNJHMFnFVKsO4xWOdIs/pub?gid=1655759976&single=true&output=csv"

```

In [ ]:
ipl_matches = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vRy2DUdUbaKx_Co9F0FSnIlyS-8kp4aKv_I0-qzNeghiZHAI_hw94gKG22XTxNJHMFnFVKsO4xWOdIs/pub?gid=1655759976&single=true&output=csv")

###`Q-6:` Make a dataframe of each team in IPL with details like - Team Name, Matches Played, Win%, Home Win%, Away Win%.
Show sorted dataframe on Win%

Replace old team name as new name before performing any tasks.
```
Delhi Daredevils ->Delhi Capitals
Kings XI Punjab -> Punjab Kings
Rising Pune Supergiants -> Rising Pune Supergiant
```

Note: Team1 represents Home team. Exclude not result matches.

In [ ]:
# code here
ipl_matches.head()

# ----------- Renaming Teams -----------

old_names = ['Delhi Daredevils','Kings XI Punjab','Rising Pune Supergiants']
new_names = ['Delhi Capitals','Punjab Kings','Rising Pune Supergiant']

mapped_names = dict(zip(old_names,new_names))
mapped_names
ipl_matches.replace(mapped_names,inplace=True)

all_teams = ipl_matches['Team1'].unique()
all_teams

res = []

for each_team in all_teams:

  # ---------- Team Name ---------
  team_name = each_team
  # ---------- Matches Played ----
  matches_played = ((ipl_matches['Team1'] == each_team) | (ipl_matches['Team2'] == each_team)).sum()
  # ---------- Win % ----
  win_perc = (((ipl_matches['WinningTeam'] == each_team).sum()) / matches_played) * 100
  res.append([team_name,matches_played,win_perc])


team_df = pd.DataFrame(res,columns=['team_name','matches_played','win_perc'])
team_df

                      team_name  matches_played   win_perc
0              Rajasthan Royals             192  50.000000
1   Royal Challengers Bangalore             226  48.230088
2           Sunrisers Hyderabad             152  49.342105
3                Delhi Capitals             224  45.982143
4           Chennai Super Kings             208  58.173077
5                Gujarat Titans              16  75.000000
6          Lucknow Super Giants              15  60.000000
7         Kolkata Knight Riders             223  51.121076
8                  Punjab Kings             218  46.330275
9                Mumbai Indians             231  56.709957
10       Rising Pune Supergiant              30  50.000000
11                Gujarat Lions              30  43.333333
12                Pune Warriors              46  26.086957
13              Deccan Chargers              75  38.666667
14         Kochi Tuskers Kerala              14  42.857143

###`Q-7:` Venues with most "no result" matches.

In [ ]:
# code here
ipl_matches.head()
ipl_matches['WinningTeam'].unique()
no_result = ipl_matches[ipl_matches['WinningTeam'].isna()]
venue_with_no_result = no_result['Venue'].head(1)
venue_with_no_result

205    M.Chinnaswamy Stadium
Name: Venue, dtype: object

###`Q-8:` Player with most appearance in final match.

`Team1Players` and `Team2Players` have all players name. It is not a list of players name instead it is str. So handle it as string.

Hint: split and strip will help; Make a series of all players in final and do value counts

In [ ]:
# code here
# ipl_matches.head()
# final_matches = ipl_matches[ipl_matches['MatchNumber'] == 'Final']
# players_played_in_final = pd.concat([final_matches['Team1Players'],final_matches['Team2Players']])

# all_players = []

# for each_series in players_played_in_final.str.split(','):
#   for each_player in each_series:
#     all_players.append(each_player.strip())

# players_series = pd.Series(all_players)
# players_series.value_counts()

ipl_matches['WinningTeam'].unique()

array(['Gujarat Titans', 'Rajasthan Royals',
       'Royal Challengers Bangalore', 'Punjab Kings', 'Mumbai Indians',
       'Lucknow Super Giants', 'Sunrisers Hyderabad', 'Delhi Capitals',
       'Kolkata Knight Riders', 'Chennai Super Kings', nan,
       'Rising Pune Supergiant', 'Gujarat Lions', 'Pune Warriors',
       'Deccan Chargers', 'Kochi Tuskers Kerala'], dtype=object)

###`Q-9:` IPL Point Table

Make a function `point_table` which take `season` as parameter and show points table in non-ascendng order of points and in ascending order of team name.

For winning - 2 Ponits;
For loosing - 0 Point
For not result both team gets 1 points.

Make dataframe which will have
`TeamName` `MatchesPlayed` `MatchesWon` `NoResult` `Points`
make `TeamName` as index.

```
season parametr should be one of these->
['2022', '2021', '2020/21', '2019', '2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011', '2009/10', '2009', '2007/08']
```

Output of two Top 2 in season 2022
```
TeamName    MatchesPlayed	MatchesWon	NoResult	Points

Gujarat Titans	    16	   12	       0	     24
Rajasthan Royals	  17	   10	       0	     20

```

In [ ]:
# code here
ipl_matches['Season']

def point_table(season):
  try:
    season_data = ipl_matches[ipl_matches['Season'] == season]
    teams_in_season = season_data['Team1'].unique()
    points_data = []

    for each_team in teams_in_season:
      TeamName = each_team
      MatchesPlayed = ((season_data['Team1'] == each_team) | (season_data['Team2'] == each_team)).sum()
      MatchesWon = (season_data['WinningTeam'] == each_team).sum()
      team_data = season_data[(season_data['Team1'] == each_team) | (season_data['Team2'] == each_team)]
      NoResult = (team_data['WinningTeam'].isna()).sum()
      Points = (MatchesWon * 2) + NoResult
      points_data.append([TeamName,MatchesPlayed,MatchesWon,NoResult,Points])

    points_data_df = pd.DataFrame(points_data,columns=['TeamName','MatchesPlayed','MatchesWon','NoResult','Points'])
    points_data_df = points_data_df.sort_values(['Points','TeamName'],ascending=[False,True])
    points_data_df.set_index('TeamName',inplace=True)
    return points_data_df
  except:
    raise KeyError('No Such Season Found')

res = point_table('2022')
print(res.head(2))

                  MatchesPlayed  MatchesWon  NoResult  Points
TeamName
Gujarat Titans               16          12         0      24
Rajasthan Royals             17          10         0      20

###`Q-10:` IPL Point Table cont.
Extend the above IPL Point Table with an extra column as `SeasonPosition`

Team below top 4 after sorting on `Points` and then on `TeamName` Will have same `SeasonPosition` as there rank. use rank function.

Teams in Top four will have `SeasonPosition` as:
```
    'Winner' - Team won final
    'Runner' - Team lost Final
    3 - Losing Team in Qualifier2
    4 - Losing Team in Eliminator
```

For changing value of pariticular cell use `df.at[row_index, col_label] = value`

Output of two Top 2 in season 2022. Your result should have all teams.
```
TeamName    MatchesPlayed	MatchesWon	NoResult	Points   SeasonPosition

Gujarat Titans	    16	   12	       0	     24         Winner
Rajasthan Royals	  17	   10	       0	     20         Runner

```

Note: If you try to chnage value of view of any dataframe a warnig will be shown. To avoid it, make a copy of the dataframe you want to change in by `df.copy()`

In [ ]:
# code here
res = point_table('2022')
res1 = res.copy()

top_four_teams = res1.head(4)
res1['SeasonPosition'] = top_four_teams['Points'].rank(ascending=False,method='first')

res1.loc[res1['SeasonPosition'] == 1, 'SeasonPosition'] = 'Winner'
res1.loc[res1['SeasonPosition'] == 2, 'SeasonPosition'] = 'Runner'
res1.loc[(res1['SeasonPosition'] == 3), 'SeasonPosition'] = 'Losing Team in Qualifier2'
res1.loc[(res1['SeasonPosition'] == 4), 'SeasonPosition'] = 'Losing Team in Eliminator'
res1

/tmp/ipykernel_353/2382430083.py:8: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Winner' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  res1.loc[res1['SeasonPosition'] == 1, 'SeasonPosition'] = 'Winner'

,MatchesPlayed,MatchesWon,NoResult,Points,SeasonPosition
TeamName,,,,,
Gujarat Titans,16,12,0,24,Winner
Rajasthan Royals,17,10,0,20,Runner
Lucknow Super Giants,15,9,0,18,Losing Team in Qualifier2
Royal Challengers Bangalore,16,9,0,18,Losing Team in Eliminator
Delhi Capitals,14,7,0,14,NaN
Punjab Kings,14,7,0,14,NaN
Kolkata Knight Riders,14,6,0,12,NaN
Sunrisers Hyderabad,14,6,0,12,NaN
Chennai Super Kings,14,4,0,8,NaN
Mumbai Indians,14,4,0,8,NaN