## **Questions based on Titanic Dataset:**

To read the dataset as csv, use the below code:

```python
import pandas as pd

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)
```

In [3]:
import numpy as np
import pandas as pd

In [4]:
url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"

titanic = pd.read_csv(url)
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### `Q-1:` Using `groupby` make groups using the `"Pclass"` column and find out the average age and total number of missing values in the `"Age"` column for every group.

In [10]:
# code here
p_class = titanic.groupby('Pclass')
# average_age = round(p_class['Age'].mean(),2)
# total_missing_age_values = p_class['Age'].apply(lambda x : x.isna().sum())
# total_missing_age_values

for group in list(p_class.groups.keys()):
  print(f"{group} -> {p_class.get_group(group)['Age'].mean()} -> {p_class.get_group(group)['Age'].isna().sum()}")

1 -> 38.233440860215055 -> 30
2 -> 29.87763005780347 -> 11
3 -> 25.14061971830986 -> 136

### `Q-2:` Using `groupby` make groups using the `"Pclass"` column and fill every group's `"Embarked"` column's missing values with the mode value of that group. After that, print every group's `"Embarked"` column's value counts in ascending order.

In [16]:
# code here
# def fillMissingVal(group):
# 	each_group_embarked_col = group['Embarked']
# 	mode_val = group['Embarked'].mode()[0]
# 	each_group_embarked_col.fillna(mode_val,inplace=True)
# 	return group


# filled_df = p_class.apply(fillMissingVal)
# filled_df['Embarked'].isna().sum()

for group in list(p_class.groups.keys()):
	p_class.get_group(group)['Embarked'].fillna(p_class.get_group(group)['Embarked'].mode(),inplace=True)
	print(p_class.get_group(group)['Embarked'].value_counts(ascending=True))

Embarked
Q      2
C     85
S    127
Name: count, dtype: int64
Embarked
Q      3
C     17
S    164
Name: count, dtype: int64
Embarked
C     66
Q     72
S    353
Name: count, dtype: int64

/tmp/ipykernel_3527/3043552328.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p_class.get_group(group)['Embarked'].fillna(p_class.get_group(group)['Embarked'].mode(),inplace=True)
/tmp/ipykernel_3527/3043552328.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p_class.get_group(group)['Embarked'].fillna(p_class.get_group(group)['Embarked'].mode(),inplace=True)
/tmp/ipykernel_3527/3043552328.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p_class.get_group(group)['Embarked'].fillna(p_class.get_group(group)['Embarked'].mode(),inplace=True)

### `Q-3:` Make groups based on `"Embarked"` column. And for each of this embarked group, make another group based on `"Pclass"` and find out the average fare (round off up to 2 decimal places) for each "Pclass" for each group of "Embarked".

**Sample Output:**

```bash
{'C': {1: 105, 2: 25, 3: 11},
 'Q': {1: 90, 2: 12, 3: 11},
 'S': {1: 70, 2: 20, 3: 15}}
```

In [20]:
# code here
# res = (
# 	titanic.groupby(['Embarked','Pclass'])['Fare']
# 		   .mean()
# 		   .round(2)
# 		   .unstack()
# 		   .to_dict('index')
# )
# res


fares = {}
embarked_groupby = titanic.groupby('Embarked')

for embarked_group in list(embarked_groupby.groups.keys()):
	p_class_groupby = embarked_groupby.get_group(embarked_group).groupby('Pclass')
	avg_fares = {}
	for p_class_group in list(p_class.groups.keys()):
		avg_fare = p_class_groupby.get_group(p_class_group)['Fare'].mean().round(2)
		avg_fares[p_class_group] = int(avg_fare)
	fares[embarked_group] = avg_fares

fares

{'C': {1: 104, 2: 25, 3: 11},
 'Q': {1: 90, 2: 12, 3: 11},
 'S': {1: 70, 2: 20, 3: 14}}

## **Questions Based on Fifa Worldcup - 2022 Dataset:**

You can read the dataset by using the below sample code

```python
import pandas as pd

fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")
```

### `Q-4:` Perform `groupby` based on the `"Team"` column and then perform Z Normalization on top of the below columns of each group:
1. Passes
2. Passes Completed
3. Attempted Line Breaks
4. Completed Line Breaks

You have to make a python function named `z_normalization` which takes two arguments:

1. *group:* Every group that you have created
2. *cols_to_perform:* This parameter takes a list of columns on which you have to perform the Z-Normalization.

For this problem, you have to use th `apply()` method.

$\Large Z \ - \ Normalization = \frac{X_i - \mu}{std} $

After that find out the below values for each group:
- minimum "Passess"
- maximum "Passess"
- minimum "Yellow Cards"
- maximum "Yellow cards"
- average "Yellow Cards"
- maximum "Attempted Line Breaks"
- minimum "Attempted Line Breaks"
- standardard deviation of "Attempted Line Breaks"
- average Possession

In [34]:
# code here
fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")
fifa_df


team_groupby = fifa_df.groupby('Team')

fifa_df.columns

def z_normalization(group, cols):
    group = group.copy()
    # now normalize
    for each_col in cols:
        mean = group[each_col].mean()
        std = group[each_col].std()
        group[each_col] = (group[each_col] - mean) / std

    return group


cols = ['Passes', 'Passes Completed', 'Attempted Line Breaks', 'Completed Line Breaks']
z_normalized_df = team_groupby.apply(z_normalization, cols)
z_normalized_df

team_groupby.agg({
    'Passes' : ['min','max'],
    'Yellow Cards' : ['min','max','mean'],
    'Attempted Line Breaks' : ['min','max','std'],
    'Possession (%)' : 'mean'
})

/tmp/ipykernel_3527/2074923122.py:22: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  z_normalized_df = team_groupby.apply(z_normalization, cols)

               Passes       Yellow Cards               Attempted Line Breaks  \
                  min   max          min max      mean                   min
Team
Argentina         408   862            0   8  2.285714                   141
Australia         286   466            0   3  1.750000                   133
Belgium           512   685            1   3  1.666667                   167
Brazil            548   695            0   3  1.200000                   164
Cameroon          295   500            1   5  2.666667                   144
Canada            448   536            2   4  2.666667                   102
Costa Rica        231   454            1   3  2.000000                    86
Croatia           461   724            0   2  1.142857                    97
Denmark           537   650            1   2  1.666667                   173
Ecuador           429   484            0   2  1.000000                   143
England           508   810            0   1  0.200000                   133
France            358   734            0   3  1.142857                   126
Germany           352   827            0   3  1.000000                   143
Ghana             319   460            2   4  2.666667                   122
Iran              232   463            2   3  2.333333                    56
Japan             225   591            0   3  1.500000                   104
Korea Republic    359   548            1   2  1.500000                   139
Mexico            356   500            1   4  2.333333                   127
Morocco           229   583            0   3  1.285714                   128
Netherlands       403   786            0   4  1.800000                   168
Poland            303   466            1   3  1.750000                    79
Portugal          461   678            0   3  1.200000                   165
Qatar             424   457            0   4  2.333333                   159
Saudi Arabia      267   560            2   6  4.666667                   147
Senegal           277   511            1   3  1.750000                   143
Serbia            403   513            2   7  4.000000                   140
Spain             647  1070            0   1  0.500000                   186
Switzerland       403   512            1   4  2.250000                   157
Tunisia           328   501            1   3  1.666667                   153
United States     427   572            0   4  1.250000                   143
Uruguay           390   528            1   3  2.000000                   146
Wales             325   508            1   2  1.666667                   104

                               Possession (%)
                max        std           mean
Team
Argentina       249  38.774685      49.285714
Australia       171  17.682383      31.250000
Belgium         195  14.422205      49.000000
Brazil          193  10.691118      50.400000
Cameroon        182  19.857828      38.333333
Canada          176  37.753587      44.333333
Costa Rica      154  38.974351      27.333333
Croatia         259  54.499891      47.428571
Denmark         241  34.000000      51.333333
Ecuador         177  17.009801      42.666667
England         208  29.676590      57.200000
France          179  21.407609      44.857143
Germany         256  56.624494      53.000000
Ghana           188  33.020196      37.000000
Iran            195  77.526340      31.666667
Japan           253  64.048810      30.250000
Korea Republic  201  27.072434      42.250000
Mexico          198  40.706265      46.666667
Morocco         157  10.641339      34.285714
Netherlands     198  12.759310      44.000000
Poland          156  36.326070      32.000000
Portugal        197  13.049904      53.800000
Qatar           174   7.767453      39.333333
Saudi Arabia    205  29.022979      36.666667
Senegal         184  16.938615      38.500000
Serbia          184  22.188586      42.666667
Spain           237  24.289916      67.000000
Switzerland     178   9.032349      43.000000
Tunisia         200  24.419937      38.666667
United States   204  27.693260      47.000000
Uruguay         186  22.030282      41.000000
Wales           208  53.028294      41.000000

## **Questions on IPL wala dataset**

ball by ball dataset - https://drive.google.com/file/d/1-kvv_9KCSAFWcrhS9WgTxSrURkRh6GNt/view?usp=share_link

In [36]:
file_id = '1-kvv_9KCSAFWcrhS9WgTxSrURkRh6GNt'

# Make sure the string matches this exactly:
direct_link = f'https://drive.google.com/uc?export=download&id={file_id}'

ipl = pd.read_csv(direct_link)
ipl.head()

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam
0,1312200,Rajasthan RoyalsGujarat Titans,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
1,1312200,Rajasthan RoyalsGujarat Titans,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
2,1312200,Rajasthan RoyalsGujarat Titans,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
3,1312200,Rajasthan RoyalsGujarat Titans,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
4,1312200,Rajasthan RoyalsGujarat Titans,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans

###`Q-5:` Find batsman in below category-
* Highest score while chasing
* Best Strike rate while chasing and have faced 100+ balls


> Chasing mean team batting in second inning

In [44]:
# --------------- Highest score while chasing -----------------

chasing_innings = ipl[ipl['innings'] == 2]
highest_score_while_chasing = chasing_innings.groupby(['batter','ID'])['batsman_run'].sum().sort_values(ascending=False).head(1)

# --------------- Method - 1 for second problem -------------------

balls_faced = chasing_innings.groupby('batter').size()
batters_faced_more_than_100_balls = balls_faced[balls_faced > 100].sort_values(ascending=False)

runs = chasing_innings.groupby('batter')['total_run'].sum().sort_values(ascending=False)

strike_rate = round((runs / balls_faced) * 100,2)
strike_rate = strike_rate[balls_faced > 100].sort_values(ascending=False).head(1)
strike_rate

# --------------- Method - 2 for second problem ---------------

temp_df = chasing_innings[~(chasing_innings.extra_type == "wides")]

temp_df = temp_df.groupby('batter').agg({
    'batsman_run' : 'sum',
    'ballnumber' : 'count'
})

temp_df['Strike Rate'] = (temp_df['batsman_run'] / temp_df['ballnumber']) * 100
temp_df[temp_df['ballnumber'] >= 100].sort_values(by='Strike Rate',ascending=False).head(1)

            batsman_run  ballnumber  Strike Rate
batter
PJ Cummins          222         114   194.736842

###`Q-6` Most Successful bowler against any batsman. Find that pair of bowler and batsman.
> Most Successful in terms of dissmissal. A bowler who have dissmissed any batsman most no of times. If any two pairs have same no of dissmisal, consider runs conceded by bowler to that batsman. Those who have concede lesser runs is more successful.

In [45]:
# code here
stats = ipl.groupby(['batter', 'bowler']).agg(
    dismissals=('player_out', 'count'),
    runs_conceded=('total_run', 'sum')
)
stats = stats.sort_values(
	by=['dismissals','runs_conceded'],
	ascending=[False,True]
)
stats['Rank'] = range(1,len(stats) + 1)
stats

                           dismissals  runs_conceded   Rank
batter     bowler
RG Sharma  SP Narine                8            140      1
PA Patel   B Kumar                  7             72      2
MS Dhoni   Z Khan                   7             78      3
V Kohli    Sandeep Sharma           7             79      4
RG Sharma  A Mishra                 7             87      5
...                               ...            ...    ...
N Rana     R Ashwin                 0            101  24209
KD Karthik JD Unadkat               0            106  24210
SA Yadav   R Ashwin                 0            109  24211
SR Watson  Sandeep Sharma           0            109  24212
KL Rahul   DL Chahar                0            124  24213

[24213 rows x 3 columns]

###`Q-7`: Most successful batting pair in IPL. Batting pair who have scored most runs playing together.

In [ ]:
# code here
batting_pair = ipl.groupby(['batter','non-striker'])['total_run'].sum().sort_values(ascending=False)
batting_pair

batter          non-striker
AB de Villiers  V Kohli           1623
CH Gayle        V Kohli           1617
V Kohli         AB de Villiers    1511
DA Warner       S Dhawan          1420
V Kohli         CH Gayle          1185
                                  ...
P Negi          TG Southee           0
KM Jadhav       AF Milne             0
KK Nair         K Rabada             0
SP Jackson      SW Billings          0
Z Khan          S Aravind            0
Name: total_run, Length: 8062, dtype: int64

###`Q-8:` Make a dataframe for all batting pairs played together.
```
Batsman1 Batsman2 Runs Avg StrikeRate
```

> Just to ease this question you can count wide-balls for strike rate.

In [51]:
# code here

pairs = ipl.groupby(['batter','non-striker']).agg({
		 "total_run" : "sum",
		 "ballnumber" : "count",
		 "isWicketDelivery" : "sum"
}).reset_index()

pairs["Batsman1"]  = pairs["batter"]
pairs["Batsman2"]  = pairs["non-striker"]
pairs["Runs"] = pairs['total_run']
pairs["StrikeRate"] = (pairs["Runs"] / pairs["ballnumber"]) * 100
pairs["Avg"] = pairs["Runs"] / pairs["isWicketDelivery"]
pairs.sort_values(by='StrikeRate',ascending=False)
pairs[["Batsman1","Batsman2","Runs","Avg","StrikeRate"]]

            Batsman1         Batsman2  Runs   Avg  StrikeRate
0     A Ashish Reddy         A Mishra    19   inf  126.666667
1     A Ashish Reddy  AA Jhunjhunwala     3   inf  100.000000
2     A Ashish Reddy         CL White     3   inf  100.000000
3     A Ashish Reddy     DB Ravi Teja     6   inf  200.000000
4     A Ashish Reddy        DJG Sammy    26  26.0  144.444444
...              ...              ...   ...   ...         ...
8057          Z Khan        S Aravind     0   0.0    0.000000
8058          Z Khan         S Nadeem     3   3.0   60.000000
8059          Z Khan       SL Malinga    17  17.0  212.500000
8060          Z Khan     SR Tendulkar     2   2.0   66.666667
8061          Z Khan        SS Tiwary    21  10.5   84.000000

[8062 rows x 5 columns]