In [10]:
import numpy as np
import pandas as pd
import scipy.stats as stats

# Example 1
***A researcher wants to investigate if there is an association b/w the level of education (categorical variable) and the preference of particular exercise (categorical variable) among the group of 150 individuals. The researcher collects the following sample and creates contingency table***

| Education        | Yoga | Running | Swimming | Total |
|------------------|-----:|--------:|---------:|------:|
| High School      | 15   | 20      | 10       | 45    |
| Bachelor's       | 20   | 30      | 15       | 65    |
| Master's or PhD  | 5    | 15      | 20       | 40    |
| **Total**        | **40** | **65** | **45** | **150** |

## Test Starts

In [ ]:
# H0 -> There is significant association b/w Education level and preference for exercise
# H1 -> There is no significant association b/w Education level and preference for exercise

In [13]:
observed = pd.DataFrame(
    {
        "Yoga": [15, 20, 5],
        "Running": [20, 30, 15],
        "Swimming": [10, 15, 20],
        "Total": [45, 65, 40]
    },
    index=["High School", "Bachelor's", "Master's or PhD"]
)

observed.loc["Total"] = observed.sum()

observed

                 Yoga  Running  Swimming  Total
High School        15       20        10     45
Bachelor's         20       30        15     65
Master's or PhD     5       15        20     40
Total              40       65        45    150

In [9]:


# Row totals
row_totals = observed.sum(axis=1)

# Column totals
col_totals = observed.sum(axis=0)

# Grand total
grand_total = observed.sum().sum()

# Expected table
expected = pd.DataFrame(
    [[row_totals[i] * col_totals[j] / grand_total
      for j in range(len(col_totals))]
     for i in range(len(row_totals))],
    index=observed.index,
    columns=observed.columns
)

expected

/tmp/ipykernel_17152/1999081617.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  [[row_totals[i] * col_totals[j] / grand_total

                      Yoga    Running  Swimming  Total
High School      12.000000  19.500000      13.5   45.0
Bachelor's       17.333333  28.166667      19.5   65.0
Master's or PhD  10.666667  17.333333      12.0   40.0
Total            40.000000  65.000000      45.0  150.0

In [ ]:
# you need not to calculate the expected table it does on its own
res = stats.chi2_contingency(observed)
res

Chi2ContingencyResult(statistic=np.float64(11.89612782160859), pvalue=np.float64(0.2192286801273633), dof=9, expected_freq=array([[ 12.        ,  19.5       ,  13.5       ,  45.        ],
       [ 17.33333333,  28.16666667,  19.5       ,  65.        ],
       [ 10.66666667,  17.33333333,  12.        ,  40.        ],
       [ 40.        ,  65.        ,  45.        , 150.        ]]))

In [12]:
if res.pvalue > 0.05:
	print('Null Hypothesis Cannot Be Rejected')
else:
	print('Null Hypothesis Can Be Rejected')

Null Hypothesis Cannot Be Rejected