In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/content/Titanic-Dataset.csv')

## Joint Probability Distribution

In [5]:
pd.crosstab(df['Survived'],df['Pclass'],normalize='all')

Pclass           1         2         3       All
Survived
0         0.089787  0.108866  0.417508  0.616162
1         0.152637  0.097643  0.133558  0.383838
All       0.242424  0.206510  0.551066  1.000000

## Marginal Probability Distribution

**NOTE**:-**Here,when we do margins=True after that
at last col and last row we get marginal probability along with join probability in inner cell**

In [ ]:
pd.crosstab(df['Survived'],df['Pclass'],normalize='all',margins=True)

## Conditional Probability (Considering Pclass As Already Occured Event And Now We Are Calculating Survived|Pclass)

In [10]:
pd.crosstab(df['Survived'],df['Pclass'],normalize='columns')

Pclass          1         2         3
Survived
0         0.37037  0.527174  0.757637
1         0.62963  0.472826  0.242363

## Conditional Probability (Considering Survived As Already Occured Event And Now We Are Calculating Pclass|Survived)

In [11]:
pd.crosstab(df['Survived'],df['Pclass'],normalize='index')

Pclass           1         2         3
Survived
0         0.145719  0.176685  0.677596
1         0.397661  0.254386  0.347953